FROM node:20 AS build

WORKDIR /app

# Copy client package.json and package-lock.json
COPY ./client/package.json ./client/package-lock.json ./client/
WORKDIR /app/client
RUN npm install

# Build the React client
RUN npm run build

EXPOSE 5174

CMD ["npm", "run", "dev"]
