
FROM node:20 AS build

# 2. 작업 디렉토리를 설정합니다.
WORKDIR /app


COPY ./server /app/server


COPY ./server/node_modules /app/server/node_modules


WORKDIR /app/server
EXPOSE 1337

# 6. 서버 시작
CMD ["npm", "run", "develop"]
