# Use Node.js official image as base
FROM node:20 AS build

WORKDIR /app

# Copy server's package.json and package-lock.json
COPY ./server/package.json ./server/package-lock.json ./server/
WORKDIR /app/server
RUN npm install

# Copy environment variables
COPY ./server/.env ./

# Copy the rest of the server code
COPY ./server /app/server

EXPOSE 1337

CMD ["npm", "run", "develop"]
